### PR TITLE
Lizardkinglk

### PR DESCRIPTION
**Pull request by lizardkingLK**
## 📑 Description
I added an HTML canvas project as a contribution. Updated documentation with a new section. As a newbie to open-sourcing I am very open to suggestions and reviews.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

## 📝 Additional Information
Changes happened to readme with a new section "Html Canvas" & deleted whitespace using [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

### CODE REVIEW

**Comment by Mr-vabs** [comment]
Thanks ☺️👍

**Comment by lizardkingLK** [comment]
Thank you!

**Comment by lizardkingLK** [comment]
Can I get Hacktoberfest-approved pls?

**Comment by Mr-vabs** [comment]
I guess it's already.

**Comment by lizardkingLK** [comment]
Thanks

**Pull request merged**
